//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeSheetMangementEntities : DbContext
    {
        public TimeSheetMangementEntities()
            : base("name=TimeSheetMangementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientDetail> ClientDetails { get; set; }
        public virtual DbSet<Company_Master> Company_Master { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<Module_Details> Module_Details { get; set; }
        public virtual DbSet<Project_Details> Project_Details { get; set; }
        public virtual DbSet<TaskDeatil> TaskDeatils { get; set; }
        public virtual DbSet<Activity_Type> Activity_Type { get; set; }
        public virtual DbSet<TimeSheetsDetail> TimeSheetsDetails { get; set; }
    }
}
