//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetsDetail
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> Efforts { get; set; }
        public Nullable<int> ProductiveHrs { get; set; }
        public string ActivityComment { get; set; }
        public Nullable<int> ActId { get; set; }
    }
}
