USE [master]
GO
/****** Object:  Database [TimeSheet]    Script Date: 20/09/2020 6:13:07 PM ******/
CREATE DATABASE [TimeSheet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TimeSheet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TimeSheet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TimeSheet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TimeSheet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TimeSheet] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TimeSheet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TimeSheet] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TimeSheet] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TimeSheet] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TimeSheet] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TimeSheet] SET ARITHABORT OFF 
GO
ALTER DATABASE [TimeSheet] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TimeSheet] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TimeSheet] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TimeSheet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TimeSheet] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TimeSheet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TimeSheet] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TimeSheet] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TimeSheet] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TimeSheet] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TimeSheet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TimeSheet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TimeSheet] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TimeSheet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TimeSheet] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TimeSheet] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TimeSheet] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TimeSheet] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TimeSheet] SET  MULTI_USER 
GO
ALTER DATABASE [TimeSheet] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TimeSheet] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TimeSheet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TimeSheet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TimeSheet] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TimeSheet] SET QUERY_STORE = OFF
GO
USE [TimeSheet]
GO
/****** Object:  Table [dbo].[ClientDetails]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClientDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientName] [nvarchar](200) NULL,
	[CompanyId] [int] NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_ClientDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Company_Master]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company_Master](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [nvarchar](200) NULL,
 CONSTRAINT [PK_Company_Master] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmployeeDetails]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmpName] [nvarchar](200) NULL,
	[Designation] [nvarchar](200) NULL,
 CONSTRAINT [PK_EmployeeDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Module_Details]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Module_Details](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Modules] [nvarchar](100) NULL,
	[ProjectId] [int] NULL,
 CONSTRAINT [PK_Module_Details] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Project_Details]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Project_Details](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [nvarchar](200) NULL,
	[ClientId] [int] NULL,
 CONSTRAINT [PK_Project_Details] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaskDeatils]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskDeatils](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TaskName] [nvarchar](200) NULL,
	[Description] [nvarchar](max) NULL,
	[PlannedStartDate] [date] NULL,
	[PlannedEndDate] [date] NULL,
	[PlannedEfforts] [int] NULL,
	[ModuleId] [int] NULL,
 CONSTRAINT [PK_TaskDeatils] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TimeSheetsDetails]    Script Date: 20/09/2020 6:13:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TimeSheetsDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmpId] [int] NULL,
	[TaskId] [int] NULL,
	[ActualStartDate] [date] NULL,
	[ActualEndDate] [date] NULL,
	[Efforts] [int] NULL,
	[ProductiveHrs] [int] NULL,
	[TypeOfActivity] [nvarchar](500) NULL,
 CONSTRAINT [PK_TimeSheetsDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TimeSheet] SET  READ_WRITE 
GO
